### ISSUE TITLE
Multiline Cert Request

### ISSUE THREAD

**Issue by revpixel** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#1]
Would like to see a change where I'm able to create a mulit domain request in one line. Un the cert util you can do this with coma separation.

The current ACME client allows for example domain.com, sub.domain.com, *.domain2.com 

to all be requested n the same single certificate

**Comment by rcladmin** [comment]
Currently Lets Encrypt Auto does not support multiple sub-domains on a single certificate. You can however, create one sub-domain per certificate at a time.

**Comment by revpixel** [comment]
Well it does. Hence my feature request. It has for a while now. 

certbot -d domain.xyz -d otherdomain.science -d another.us -d *.woldcard.com

**Comment by rcladmin** [comment]
Yes, Lets Encrypt supports multiple sub-domains in a single certificate. But our SaaS app for Azure called 'Lets Encrypt **Auto**' only supports one certificate for an Azure Web App. The reason being is that our app is tightly coupled to a single App Service and SSL bindings were designed to be a single certificate to a single web app. In our SaaS app you can only create a bind one certificate at a time to a web app.
