### ISSUE TITLE
Where do I get a value for  _acme-challenge?

### ISSUE THREAD

**Issue by myrabyte** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#10]
** What is the error message ?
Error:Failed to create certificate for host : XXXXXX.com with Azure KeyVault. Could not validate domain for XXXXXX.com with challenge dns-01, status reported : Invalid. {"Type":"urn:ietf:params:acme:error:dns","Detail":"DNS problem: NXDOMAIN looking up TXT for _acme-challenge.XXXXXX.com - check that a DNS record exists for this domain","Identifier":null,"Subproblems":null,"Status":400}

How do I know which value to enter into my _acme-challenge.XXXXXX.com ???  I couldn't find that info anywhere.

**Comment by myrabyte** [comment]
And now I'm getting Failed to create stand alone certificate order for host : XXXXXX.com. {"Type":"urn:ietf:params:acme:error:rateLimited","Detail":"Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/","Identifier":null,"Subproblems":null,"Status":429}


nice

**Comment by myrabyte** [comment]
When I try to generate certificate manually and select DNS, it gives me what to add into TXT record. But it doesn't do it for key vault certificate.

**Comment by rcladmin** [comment]
The 'Azure Key Vault' option automatically adds the the TXT record to the Azure DNS Zone.

**Comment by myrabyte** [comment]
> The 'Azure Key Vault' option automatically adds the the TXT record to your Azure DNS Zone.

Interesting...  Didn't seem to have happened in my case. I guess I have to recreate the vault now? Regardless, it would be really nice if there was an option to manually add the record.

**Comment by rcladmin** [comment]
If you want to manually create a certificate, you can use the 'Stand Alone' certificate options. Add the TXT record manually to your DNS and create the certificate. Then, you can download the certificate and upload it to your Azure Key Vault.
