### ISSUE TITLE
Erro to generate SSL

### ISSUE THREAD

**Issue by carloscds** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#12]
** What is the error message ?

Failed to renew certificate : api.gotaskfly.com at: 6/2/2020 12:01:41 AM. Failed to create certificate : api.gotaskfly.com. Could not validate domain for xxx.xxxy.com with challenge http-01, status reported : Invalid. {"Type":"urn:ietf:params:acme:error:connection","Detail":"Fetching https://xxx.xxx.com/.well-known/acme-challenge/Ez3Z8FfRNluFJAz-28BAAo1ssVDS_Wqk8cpqYrzpvs8: Connection reset by peer","Identifier":null,"Subproblems":null,"Status":400}
--

** What is your issue ?
All certificates was delete and they are not expired. This is very, very, complicated!!!

**Comment by rcladmin** [comment]
20 days before a certificate expires it will be deleted and re-created. If the re-creation failed, you will end up with a deleted certificate. Try to manually re-create the certificate and tell me if you encounter the same error.

**Comment by rcladmin** [comment]
You server may be experiencing high traffic or temporarily went down, resulting in 'Connection reset by peer'. You would need to manually re-create the certificate at this point.

**Comment by carloscds** [comment]
@rcladmin Ok,but your software DELETED a valid certificate. This is a big problem and you need yo fix this. I can't create a new certificate because I receive an error!

**Comment by carloscds** [comment]
@rcladmin And you delete configuration of https://letsencrypt-auto.azurewebsites.net/. You cannot do this.

**Comment by rcladmin** [comment]
Failure to renew the certificate will result in automatic deletion of the certificate, to allow for manual renewal.

**Comment by rcladmin** [comment]
Could you check your site configuration. It seems that your site if forcing a redirection of http to https on you 'well-known' endpoint. It may be resulting in SSL and other errors, will investigate this.

**Comment by carloscds** [comment]
@rcladmin No changes on your websites. I need to create every certificates again. I don't have probem to create a certificate, and yes, site force https.

**Comment by rcladmin** [comment]
The problem is that for HTTP-01 validation, the ACME server is trying to access the http but is being redirected to https. This may result in a SSL error or some type of redirect error. This will not happen with DNS-01 challenge. Investigating this, will get back to you with my findings. Please try to re-create your failed renewals, and tell me if you are getting the https or redirect errors, will try to help you resolve them.

**Comment by carloscds** [comment]
@rcladmin I already recreate them. Let me know your fix about this, because I can't stop business because of this, ok!

**Comment by rcladmin** [comment]
ok, I will get back to you in a few days with a solution.

**Comment by rcladmin** [comment]
The automatic certificate renewal process is now updated as follows:

1. Certificates will renew 20 days before they expire
2. If the renewal fails, the exiting certificate will not be deleted
3. An email will be sent to the issuers email address based on the CSR Info, notifying the issuer to manually update the certificate before it expires

**Comment by carloscds** [comment]
@rcladmin Good changes! I need to do something ?
