### ISSUE TITLE
Could not retrieve your Azure subscriptions. Your Service Principal may be incorrect. 

### ISSUE THREAD

**Issue by Shanmuganath** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#13]
** What is the error message ?
Could not retrieve your Azure subscriptions. Your Service Principal may be incorrect. 

** What is your issue ?
I could not  Create SSL/TLS certificates for Key Vault in Azure.

I tried again fresh registration of Lets-Encrypt-Auto, getting the same above error.

**Comment by rcladmin** [comment]
what is your username?

**Comment by Shanmuganath** [comment]
my username is shan@meeraskillangels.onmicrosoft.com

**Comment by Shanmuganath** [comment]
hello Anil,
                     please check the screen shot attached.
![error](https://user-images.githubusercontent.com/67467315/86191898-d81b9a00-bb65-11ea-9fe8-4c9ae090417d.png)

**Comment by rcladmin** [comment]
The tenant id used may not contain any subscriptions. You need to create the service principal in the tenant that contains the subscription. Check the subscription to see if the 'Directory' is the same as the Active Directory that you created the service principal in.

**Comment by Shanmuganath** [comment]
hello Anil,

                      I have checked my subscription in Azure Active Directory, I have given the proper Client ID, Tenant ID and secret key, I am in same Directory in subscription. pls explain where should I get support in Azure.

**Comment by rcladmin** [comment]
Could you provide the following information for the subscription in your tenant from the 'Overview' page : Directory, SubscriptionID, Status.

And then provide for the Active Directory in which you created the service principal : Name, Primary domain from the 'Overview' page.

**Comment by Shanmuganath** [comment]
![subcription](https://user-images.githubusercontent.com/67467315/86264298-f2925980-bbdf-11ea-99a6-a6de7d06f2c0.png)
![default directory](https://user-images.githubusercontent.com/67467315/86264323-fa51fe00-bbdf-11ea-9e21-3f384ea64ce6.png)

**Comment by rcladmin** [comment]
For the service principal 'App registration' in Azure Active Directory what is the value for 'Implicit grant' in the 'Authentication' section.

Are there any locks (Read/Delete) set on the subscription?

**Comment by Shanmuganath** [comment]
![permission](https://user-images.githubusercontent.com/67467315/86306348-aff96d00-bc31-11ea-90d8-cbbc4ed1b707.png)

**Comment by rcladmin** [comment]
For the App Registration, can I see the 'Authentication' values, scroll down to the 'Implicit grants'

**Comment by Shanmuganath** [comment]
![auth](https://user-images.githubusercontent.com/67467315/86381437-f8a13c80-bcaa-11ea-9de9-5e2b2430d014.png)

**Comment by rcladmin** [comment]
Can you scrooll down the page to show 'Implicit grants'

**Comment by Shanmuganath** [comment]
Can we have a screen share, please let me know your free time.

**Comment by rcladmin** [comment]
we can do it now, what screen share app do you use?

**Comment by Shanmuganath** [comment]
yes I use Skype , Teams

**Comment by rcladmin** [comment]
can you invite me in Teams right now?

**Comment by Shanmuganath** [comment]
it shows offline , I have sent hello now

**Comment by Shanmuganath** [comment]
my ID shan@edsix.onmicrosoft.com

**Comment by rcladmin** [comment]
Service Principal must be added to Subscription with IAM
