### ISSUE TITLE
Cannot able to connect with let us encrypt account from Azure

### ISSUE THREAD

**Issue by thamaraiEd** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#14]
![letusenc_error](https://user-images.githubusercontent.com/62419000/86517938-a3039600-be4a-11ea-8f2b-539ccdd575ea.PNG)

Getting above error when i am trying to manage my account from Azure. Please consider this as priority, i am getting issue in my production links

**Comment by rcladmin** [comment]
check to see it this error is resolved
