### ISSUE TITLE
Certificates not renewing

### ISSUE THREAD

**Issue by chillyjim** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#15]
For the account jlh@troycivic.org, the certificates that have been created are not being auto-renewed, and are showing "Manual" for renewal. How do I set this for automatic renewal?

**Comment by rcladmin** [comment]
Certificates created with the mode 'Stand Alone Certificate' are not automatically renewed. They must be manually deleted and renewed. To automatically renew a certificate you must select a mode that will allow for automatic renewal. These include 'Azure App Services','Azure DNS','Azure Key Vault' and 'HTTP-01 + API'
