### ISSUE TITLE
Lets Encrypt Auto Deleting Custom Domain

### ISSUE THREAD

**Issue by gcliv** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#18]
I'm having a problem with custom domains disappearing and the logs seem to indicate that the let's encrypt auto client is deleting the custom domains. Is this a problem or do I just need an explanation of the workflow and need to fix something in my configuration?

**Comment by rcladmin** [comment]
Are you creating certificates for App Service? What challenge type are you using "HTTP" or "DNS".

**Comment by gcliv** [comment]
App Service and I think a handful of them may have been HTTP, but we'd like to use all DNS

**Comment by rcladmin** [comment]
When are the custom domain 'Disappearing'. Can you explain what you are doing before the domains disappear.

**Comment by gcliv** [comment]
I don't believe I am doing anything, I think its happening when the cert was trying to auto-renew. From azure event log:

    Operation name
    Delete Web Apps Hostname Bindings
    Time stamp
    Fri Jul 17 2020 07:02:24 GMT-0500 (Central Daylight Time)
    Event initiated by
    lets-encrypt-auto-client
    Error code
    InternalServerError
    Message
    <Error><Message>An error has occurred.</Message></Error>
