### ISSUE TITLE
I am not getting the new certificate creation page, it asks for credentials upon providing, the page does not change from Home page.

### ISSUE THREAD

**Issue by Shanmuganath** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#19]
my username : shan@meeraskillangels.onmicrosoft.com

I want to create new certificate, could not proceed after providing the login credentials.

**Comment by Shanmuganath** [comment]
I could not create certificate using the Azure Key vault option, other options Azure DNS, Azure App services are working.

**Comment by rcladmin** [comment]
Did you provide the Access Policy for your logged in username to Azure Key Vault to manage certificates. You can follow the instructions here : https://rcl-letsencrypt-auto-ssl.github.io/Lets-Encrypt-Auto/5_2_certificates_keyvault.html#step-3-set-access-policy

**Comment by Shanmuganath** [comment]
Yes, I have access policy provided, I was able to create new certificate on 20/07/2020 in Key vault. I have issue from today 21/07/2020 morning 8am IST.

**Comment by rcladmin** [comment]
Can you post the error you are receiving.

**Comment by Shanmuganath** [comment]
I am not getting error, when I click on Create new Certificate link it searches the page and come back to Home page. And now when I login I am getting his error.
![error](https://user-images.githubusercontent.com/67467315/88081580-31dc1680-cb9e-11ea-950a-96c62ce62bf7.png)

**Comment by Shanmuganath** [comment]
![error](https://user-images.githubusercontent.com/67467315/88081651-533d0280-cb9e-11ea-8eb9-277d8cf45c86.png)

**Comment by Shanmuganath** [comment]
Do you need to view issue, I can do screen share

**Comment by rcladmin** [comment]
Try it now and post the error page, if i can't solve it, we can do screen share

**Comment by Shanmuganath** [comment]
yes same issue, there is no error, instead I am redirected to Home page after clicking the Create New SSL certificate.

**Comment by rcladmin** [comment]
ok, we can do the Team Viewer screen share now

**Comment by Shanmuganath** [comment]
Teamviewer. ID. 700 383 637 

password. 5y7y3x

**Comment by rcladmin** [comment]
Consent should be provided for application to use Azure Key Vault and Access Polices should be set as follows: https://rcl-letsencrypt-auto-ssl.github.io/Lets-Encrypt-Auto/5_2_certificates_keyvault.html#step-3-set-access-policy
