### ISSUE TITLE
Error when try to reate a certificate

### ISSUE THREAD

**Issue by carloscds** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#2]
Failed to create certificate for webinar.cds-software.com.br. Failed response : NotFound in AzureCertificateService, CreateHostNameBindingAsync

**Comment by rcladmin** [comment]
There is a new version of Lets Encrypt Auto to be released soon. Will investigate this with the new release.

**Comment by carloscds** [comment]
@rcladmin And for now I can't use, right?

**Comment by rcladmin** [comment]
@carloscds  are you using HTTP or DNS challenge ?

**Comment by rcladmin** [comment]
It seems the issue may be stemming from the '.com.br'. What is expected is '.com', will try to resolve this.

**Comment by carloscds** [comment]
@rcladmin HTTP

**Comment by carloscds** [comment]
@rcladmin I have .com and .com.br and with Let's Encrypt extention for appservice I do not problem.

**Comment by rcladmin** [comment]
Can you retry creating certificate for : webinar.cds-software.com.br with the new version of Lets Encrypt Auto with HTTP challenge. Please post error message if it fails.

**Comment by rcladmin** [comment]
@carloscds  I checked the Host Binding Service for your hostname and it seems to be working. Can you try again, make sure your hostname does not have any trailing or leading balnk spaces. Send me the error message. I updated the app to provide more detailed error messages in text/json format. It will help to debug the problem.

**Comment by carloscds** [comment]
@rcladmin No spaces. This error:
Failed to create certificate for host : webinar.cds-software.com.br. Failed response : NotFound in IAzureHostBindingService. {"Code":"NotFound","Message":"Certificate 1C6351CEE00378F7F977DA7F51708538B80E602B was not found.","Target":null,"Details":[{"Message":"Certificate 1C6351CEE00378F7F977DA7F51708538B80E602B was not found."},{"Code":"NotFound"},{"ErrorEntity":{"ExtendedCode":"04031","MessageTemplate":"Certificate {0} was not found.","Parameters":["1C6351CEE00378F7F977DA7F51708538B80E602B"],"Code":"NotFound","Message":"Certificate 1C6351CEE00378F7F977DA7F51708538B80E602B was not found."}}],"Innererror":null}

**Comment by rcladmin** [comment]
@carloscds  , thanks for your patience. Can you try creating the certificate one last time and post me the error message. I need to get the source method to resolve this error.

**Comment by rcladmin** [comment]
The certificate is being created and added to Azure App Service Plan. But the Web App cannot find the certificate to bind it. Is the Location (eg. East US 2) for the App Service Plan and Web App the same or differenet?

**Comment by carloscds** [comment]
@rcladmin AppService and Plan are in same current region: East US.
I receive same error message:

Failed to create certificate for host : webinar.cds-software.com.br. Failed response : NotFound in IAzureHostBindingService : UpdateAsync. {"Code":"NotFound","Message":"Certificate 72F5847F005F64F13EA97B62414F69A2E89081E5 was not found.","Target":null,"Details":[{"Message":"Certificate 72F5847F005F64F13EA97B62414F69A2E89081E5 was not found."},{"Code":"NotFound"},{"ErrorEntity":{"ExtendedCode":"04031","MessageTemplate":"Certificate {0} was not found.","Parameters":["72F5847F005F64F13EA97B62414F69A2E89081E5"],"Code":"NotFound","Message":"Certificate 72F5847F005F64F13EA97B62414F69A2E89081E5 was not found."}}],"Innererror":null}
--

**Comment by rcladmin** [comment]
The SSL certificate is being created in a webspace CDSEastUS-EastUSWebspace.  Your app plan Default1 is in the webspace EastUSWebspace. Ideally, the app plan and certificate should be in the same webspace.

A possible workaround is this:

- Create a new standard App Plan Service in resource group CDSEastUs in region EastUS
- Move or re-publish your websites from the existing Default1 web plan to the new app plan
- Retry creating SSL certificates with Lets Encrypt Auto for your websites in the new plan

I have not tested this. I am not quite sure if it will work, it just a hunch I have.

**Comment by rcladmin** [comment]
you can give it one last try before you consider the workaround above. I tried to force app to install cert in your webspace, but the Azure API may stock with its default behavior.

**Comment by carloscds** [comment]
@rcladmin Now I can get to issue certificate. Thanks for your help.
