### ISSUE TITLE
Any "A" record I use I am told doesn't exist

### ISSUE THREAD

**Issue by chillyjim** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#21]
** What is the error message ?
[Copy and paste the error message here]
Failure in AzureService in AzureDNSService : Get. Failed response : NotFound in AzureDNSService : Get. {"code":"NotFound","message":"The resource record 'scotland' does not exist in resource group 'jims-dns' of subscription 'e8df460c-4acd-481b-88a6-bc06f33d2e8d'."}

** What is your issue ?
These records show in the azure portal and come back with the correct address when querying
[DNS2.pdf](https://github.com/rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto/files/4963529/DNS2.pdf)
[dns1.pdf](https://github.com/rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto/files/4963530/dns1.pdf)

 external DNS servers.

**Comment by rcladmin** [comment]
Are you trying to create a TLS/SSL certificate for a subdomain scotland.chillyjim.org using the DNS option?

**Comment by chillyjim** [comment]
The Azure DNS option, yes. For host name I have tried the hostname FQDN and just the DN (what returned '@' isn't a record. I'm sure I'm not parcing the docs correctly. Thanks.

**Comment by rcladmin** [comment]
What is the domain or subdomain you are trying to create the TLS/SSL Certificate for ? Is it scotland.chillyjim.org ?

**Comment by chillyjim** [comment]
What I really want is *.chillyjim.org, If I need to go host by host scotland.chillyjim.org is where I will be starting.

**Comment by rcladmin** [comment]
If you need to create a TLS/SSL certificate for the sub domain scotland.chillyjim.org, the host name you should enter is 'scotland.chillyjim.org' and not 'scotland' . If you need a wild card * certificate you should enter *.chillyjim.org and use a DNS challenge type in any of the methods allowed.
