### ISSUE TITLE
Error on creating app service certificate with DNS challenge

### ISSUE THREAD

**Issue by gcliv** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#23]
"DNS. Object reference not set to an instance of an object."

**Comment by gcliv** [comment]
Also getting it on HTTP challenges: Error:Failed to create app service certificate for host : <domain> on siteId : 309 with challenge : HTTP. Object reference not set to an instance of an object.

**Comment by rcladmin** [comment]
What SKU is your App Service Plan that host your application? Free, Shared, Basic or Standard?

**Comment by gcliv** [comment]
Standard

**Comment by rcladmin** [comment]
what is the host name?
