### ISSUE TITLE
Adding co-admin

### ISSUE THREAD

**Issue by gcliv** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#24]
How do I add a fellow Azure admin to my subscription in Let's Encrypt? I added them as an owner to the SaaS object but when he opens the account he is prompted to create a subscription rather than see all the existing subscription/certificates.

**Comment by rcladmin** [comment]
The application does not allow for co-admins at this time.

**Comment by gcliv** [comment]
Is it possible to transfer it to someone else then?

**Comment by rcladmin** [comment]
transferring an account is not supported at this time
