### ISSUE TITLE
HTTP Challenge Fails

### ISSUE THREAD

**Issue by gcliv** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#25]
** What is the error message ?
Error:Failed to create app service certificate for host : www.overflowworks-lookup.com on siteId : 320 with challenge : HTTP. Failure in AzureService in AzureHostnameBindingService : Put. Failed response : BadRequest in AzureHostnameBindingService : Put. {"Code":"BadRequest","Message":"A TXT record pointing from asuid.www.overflowworks-lookup.com to de84be3ec8f0d05a0ddf4cd6a08559124a91718a29e97cf20d9c5aea1f87e065 was not found.","Target":null,"Details":[{"Message":"A TXT record pointing from asuid.www.overflowworks-lookup.com to de84be3ec8f0d05a0ddf4cd6a08559124a91718a29e97cf20d9c5aea1f87e065 was not found."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"04006","MessageTemplate":"A TXT record pointing from asuid.{0} to {1} was not found.","Parameters":["www.overflowworks-lookup.com","de84be3ec8f0d05a0ddf4cd6a08559124a91718a29e97cf20d9c5aea1f87e065"],"Code":"BadRequest","Message":"A TXT record pointing from asuid.www.overflowworks-lookup.com to de84be3ec8f0d05a0ddf4cd6a08559124a91718a29e97cf20d9c5aea1f87e065 was not found."}}],"Innererror":null}

** What is your issue ?
HTTP challenge fails

**Comment by rcladmin** [comment]
I am investigating this.

**Comment by rcladmin** [comment]
You may need to re-create your custom domain with a 'asuid.www' TXT record and a 'www' domain record.
