### ISSUE TITLE
DNS Challenge Fails

### ISSUE THREAD

**Issue by gcliv** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#26]
** What is the error message ?
Failed to create app service certificate for host : www.overflowworks-lookup.com on siteId : 319 with challenge : DNS. Failure in AzureService in AzureDNSService : Put. Failed response : Conflict in AzureDNSService : Put. {"code":"Conflict","message":"The CNAME record could not be created because another record with the same name already exists in this zone."} 

** What is your issue ?
DNS challenge fails.

**Comment by rcladmin** [comment]
Try deleting the CNAME record for www and try again.

**Comment by rcladmin** [comment]
Is there another record type, A or TXT, in your DNS Zone with the same CNAME 'www' ? This will cause the failure.

**Comment by rcladmin** [comment]
Can you post image of your DNS records in your DNS Zone?
