### ISSUE TITLE
All subscriptions disappear

### ISSUE THREAD

**Issue by carloscds** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#29]
You change login to AD login and I have not "AAD" subscritptions. How can I solve this ?

**Comment by rcladmin** [comment]
What username did you use before to login?

**Comment by emramirez** [comment]
I have the same issue. My username is edgar@sinefi.mx.

**Comment by rcladmin** [comment]
@emramirez what type of account is  edgar@sinefi.mx? Do you have an AAD/Microsoft Account that you can login with? I can transfer your subscription to an account that you can login in with

**Comment by carloscds** [comment]
@rcladmin I think that tou change autentication mode and fix to AAD auth.

**Comment by rcladmin** [comment]
The system uses AAD Auth. What email are you using? Can you sign in with micrsoft? what error are you getting in sign in?

**Comment by carloscds** [comment]
@rcladmin Yes I can sign in Microsoft. This email is a live account and AAD account, but your service do not ask about "Work or School accout" or "Personal account"

**Comment by rcladmin** [comment]
The system uses the new Microsoft Identity Platform, I will investigate this and try to resolve the problem. The system does not support: PersonalMicrosoftAccount:  personal Microsoft accounts (for example, Skype, Xbox, and Outlook.com)

**Comment by carloscds** [comment]
@rcladmin Before system supported Microsoft account.

**Comment by rcladmin** [comment]
When the app moved to Microsoft Identity, they recommended : "Due to temporary differences in supported functionality, we don't recommend enabling personal Microsoft accounts for an existing registration. If you need to enable personal accounts, you can do so using the manifest editor".

Will try to enable personal accounts using the manifest editor and get back to you asap.

**Comment by rcladmin** [comment]
Are you able to login? What happens after you type in password in sign in screen?

**Comment by rcladmin** [comment]
@carloscds can you login and see if it works. Personal accounts is now enabled with Microsoft Identity Platform.

**Comment by emramirez** [comment]
> @emramirez what type of account is [edgar@sinefi.mx](mailto:edgar@sinefi.mx)? Do you have an AAD/Microsoft Account that you can login with? I can transfer your subscription to an account that you can login in with

I don't have an ADD/Microsoft Account, edgar@sinefi.mx is a Microsoft Account, I use this account to login into Azure.

**Comment by rcladmin** [comment]
@emramirez try to login now and see if it works.

**Comment by emramirez** [comment]
> @emramirez try to login now and see if it works.
It works!  Thank you!!

**Comment by emramirez** [comment]
I have successfully logged in, but when I try to create a new certificate I get an error:

Error.
An error occurred while processing your request.
Request ID: |f2e7c91d-4e87da27574bed52.

**Comment by rcladmin** [comment]
@emramirez  Try re-creating a new certificate and tell me what is the error message. You should now see a more descriptive error message.

**Comment by emramirez** [comment]
> @emramirez Try re-creating a new certificate and tell me what is the error message. You should now see a more descriptive error message this time.

Error.
An error occurred while processing your request.
Request ID: Activity.Current?.Id ?? HttpContext.TraceIdentifier : Error, AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://management.azure.com/user_impersonation offline_access openid profile' does not exist. Trace ID: d27d409c-1f5a-424a-9add-a6714081bf00 Correlation ID: 4439445b-41e8-454b-a1fc-aa86f0f9f3a0 Timestamp: 2020-08-11 22:58:49Z

**Comment by rcladmin** [comment]
ok, working to resolve this

**Comment by rcladmin** [comment]
@emramirez  can you try again and post the error

**Comment by emramirez** [comment]
> ok, working to resolve this



> @emramirez can you try again and post the error

Request ID: |8bd35315-4e928a5ec8dd3967. : GetType, AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope 'https://management.azure.com/user_impersonation offline_access openid profile' does not exist. Trace ID: d5143ca3-038b-4772-a586-392a2ff7cc00 Correlation ID: 8033a0a8-8f0d-4f4b-b275-ce716c28e7fc Timestamp: 2020-08-11 23:40:20Z

**Comment by emramirez** [comment]
> @emramirez what type of account is [edgar@sinefi.mx](mailto:edgar@sinefi.mx)? Do you have an AAD/Microsoft Account that you can login with? I can transfer your subscription to an account that you can login in with

I could try to create an ADD/Microsoft Account

**Comment by rcladmin** [comment]
@emramirez  there seems to be a problem with personal accounts. What account do you sign in to use the Azure portal?

**Comment by emramirez** [comment]
> @emramirez there seems to be a problem with personal accounts. What account do you sign in to use the Azure portal to manage your azure resources?

The same, edgar@sinefi.mx

I have created the account letsencrypt@edgarsinefi.onmicrosoft.com it is an ADD/Microsoft account

**Comment by rcladmin** [comment]
can you access the azure portal and manage your azure services with this account: letsencrypt@edgarsinefi.onmicrosoft.com

**Comment by carloscds** [comment]
@rcladmin I try to login and receive this error:
![image](https://user-images.githubusercontent.com/1697221/89968708-ea8bf780-dc2a-11ea-9669-ecfde143d500.png)

**Comment by rcladmin** [comment]
Personal accounts are giving the error

**Comment by emramirez** [comment]
> can you access the azure portal and manage your azure services with this account: [letsencrypt@edgarsinefi.onmicrosoft.com](mailto:letsencrypt@edgarsinefi.onmicrosoft.com)

I have successfully logged in, but my subscription has been disappeared.

**Comment by emramirez** [comment]
> > can you access the azure portal and manage your azure services with this account: [letsencrypt@edgarsinefi.onmicrosoft.com](mailto:letsencrypt@edgarsinefi.onmicrosoft.com)
> 
> I have successfully logged in, but my subscription has been disappeared.

I was confused, my subscription is fine, but I can't see my certificates.

**Comment by rcladmin** [comment]
@emramirez personal accounts are not supported. Do you want to transfer your account from : edgar@sinefi.mx  to : letsencrypt@edgarsinefi.onmicrosoft.com

**Comment by carloscds** [comment]
@rcladmin I can't see my subscriptions because some of them was created using Microsoft Account and your tool force login with AAD, WHY ?

**Comment by rcladmin** [comment]
@carloscds the application uses the Azure Resources API to manage DNS, Web Apps and Key Vault. The access token for the API is only issued to work/school accounts. Personal / Microsoft accounts do not seem to be supported. I was unable to resolve issues for personal accounts , so at this point the app will not support personal accounts. Previously the app used a 'Service Principal' to get the token, but stored a user's user_secret in a database with posed a security threat to the user.

As a work around, I am transferring existing subscriptions with a Personal account to a work account. I will provide instructions in a few minutes on how to transfer your account.

**Comment by carloscds** [comment]
@rcladmin No, you are wrong. One month late I can access all of my subscriptions without problem. Some update in your tool change this. Please check and fix. Using only AAD, this tool is not useful for me. I will not change all of my environment on Azure because of your tool.

**Comment by rcladmin** [comment]
To transfer a Peronal Account in the RCL Lets Encrypt App

- Create or use an existing user in your Active directory
- The user must have 'Owner' or 'Contributor' roles to all the subscriptions in your Azure Subscriptions that contain your web apps, DNS, Key Vault
- Login with the user credentials to the application
- I will transfer the the account to the user once a successful login is acheived

**Comment by rcladmin** [comment]
@emramirez  Have you created a new subscription with :   letsencrypt@edgarsinefi.onmicrosoft.com ?

**Comment by rcladmin** [comment]
@carloscds you do not need to change your Azure environment. You just need to login to the RCL Lets Encrypt application with a valid user account in your organization's Azure Active Directory.

**Comment by emramirez** [comment]
> @emramirez Have you created a new subscription with : [letsencrypt@edgarsinefi.onmicrosoft.com](mailto:letsencrypt@edgarsinefi.onmicrosoft.com) ?

No I haven’t! I just have logged with letsencrypt@edgarsinefi.onmicrosoft.com in the existing Subscription.

**Comment by carloscds** [comment]
@rcladmin I guess that you are not understand. We have two type of Azure Login: AAD and Personal Account (Live Account/Microsoft Account). Most of our enviroments use Microcoft Account and to use your tool NOW, I need to put another user (AAD) in all of this subscriptions. And then I need to change my environment. Do you understand ?

**Comment by carloscds** [comment]
@rcladmin I we have a security problem using your suggestion, because we need to create a generic account, maybe, that need many permissions under environment.

**Comment by rcladmin** [comment]
@carloscds What is the process you are using now? How do you log in to the Let's Encrypt Application? Do more that one person use the same account to login or does just one person login with the account : cds@cds-s*****,br. Is that account a 'generic' account?

**Comment by carloscds** [comment]
@rcladmin I was login using this email that you mention. This account is both, but I can select AAD or Personal. Today, in your application I can't do this.

**Comment by rcladmin** [comment]
@carloscds How may people manage certificate with the Let's Encrypt application? Is it just one person, or dow many people login with the same account  cds@cds-s*****,br

**Comment by carloscds** [comment]
@rcladmin Only me.

**Comment by rcladmin** [comment]
Ok, only you login with cds@cds-s*****,br . Are all the subcriptions in the same Azure account or are there several different Azure Accounts?

**Comment by carloscds** [comment]
@rcladmin Different, under same email.

**Comment by carloscds** [comment]
@rcladmin Look, only problem is: you change tool to use AAD auth and because of this, you remove App Authorization. But If I have many subscriptions, under different emails (AAD/Personal), this approach does not work. If I log with AAD you list all subscriptions under this account, but you need to allow to log using Personal/MS Account and do same thing. OK ?

**Comment by rcladmin** [comment]
Do you have a user account in Azure Active directory that you can use. If not can you create a user account in Azure Active Directory for you only to use?

**Comment by carloscds** [comment]
@rcladmin One last question: your application will work only with AAD accounts ? Yes or not ?

**Comment by rcladmin** [comment]
Personal Accounts / Microsoft Accounts are NOT supported by the Azure Management Service API. Only Azure Active Directory Accounts (AAD) are supported. These accounts are sometime referred to work or school accounts. These accounts are organizational accounts created in Azure Active Directory.

Do you have a user account in Azure Active directory that you can use. If not,can you create a user account in Azure Active Directory for you only to use?

**Comment by carloscds** [comment]
@rcladmin Please, change my email to cloud@cds-s******.com.br

**Comment by rcladmin** [comment]
You account has been transferred to cloud@cds-s******.com.br . Pleas login with this AAD account and confirm that you have access to your certificates

**Comment by carloscds** [comment]
@rcladmin I can login, but I can't see subscriptions. Now Im loggin with AAD account and when I log at azure portal with same account I can see subscription.

**Comment by rcladmin** [comment]
Ok, when you log in with **cloud@cds-s*********.br** , you can see your certificates?

**Comment by carloscds** [comment]
@rcladmin Certificates yes, Azure subscriptions no.

**Comment by rcladmin** [comment]
I assume you can access the 'Create Options' page. The reason you are not seeing any subscriptions, is that the AAD account does not have permissions to your subscription. To create a new web app , you must now enable access control. You can foollow this link to provide access control to your AAD account:

https://rcl-letsencrypt-auto-ssl.github.io/Lets-Encrypt-Auto/5_1_certificates_appservice.html#access-control

**Comment by carloscds** [comment]
@rcladmin This user is Contributor/Owner of subscripption.

**Comment by rcladmin** [comment]
Yes, have you enabled Contributor/Owner role for one of your subscriptions to AAD Account. If you have done that, you will be able to see that subscription.

**Comment by carloscds** [comment]
@rcladmin But I can't see. What next step to solve this?

**Comment by rcladmin** [comment]
Select one of your subscription in the 'Subscriptions' section on the Azure Portal, and add a role for AAD Account : cloud@cds-s*******.br**

This is a sample image :

![image](https://user-images.githubusercontent.com/4339259/90061297-f2dc4500-dcb3-11ea-8d63-6107d6d6aa0c.png)

The new role assignment is shown as in sample imge:

![image](https://user-images.githubusercontent.com/4339259/90061201-ce806880-dcb3-11ea-87fd-abecbe3bb76e.png)

**Comment by carloscds** [comment]
![image](https://user-images.githubusercontent.com/1697221/90061746-f32d0e00-dcbc-11ea-8cf8-ee6e618f61ca.png)

![image](https://user-images.githubusercontent.com/1697221/90061782-0344ed80-dcbd-11ea-9c42-8c5546a393e4.png)

**Comment by rcladmin** [comment]
Is the AAD account a Guest Account or a Member Account? Can you ensure that the Account is a 'Member' and not Guest.

**Comment by carloscds** [comment]
Guest

**Comment by rcladmin** [comment]
Can you either change it to a "Member" account or create a new "Member" account. I can always transfer the subscription to a new account for you.

**Comment by carloscds** [comment]
Please, send-me an email to continue this, I can't put information on a public site. Tks.

**Comment by rcladmin** [comment]
rcl@rclapp.com . I also have TeamViewer to help you remotely.
