### ISSUE TITLE
Issue in creating stand alone SSL certificate

### ISSUE THREAD

**Issue by Ruchi-Bod** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#30]
I am trying to create a stand alone certificate but its raising error while varifying the domain like below :
Failed to create certificate with target Stand ALone for host : analytics.clicflyer.com. Could not validate domain for analytics.clicflyer.com with challenge http-01, status reported : Invalid. {"Type":"urn:ietf:params:acme:error:unauthorized","Detail":"Invalid response from http://analytics.clicflyer.com/.well-known/acme-challenge/Amt1jnZaYicwCeARSaRCW5FYfjIdli7MQzltkJCbqPc [52.138.145.153]: \"<!DOCTYPE html>\\r\\n<html>\\r\\n<head>\\r\\n <meta charset=\\\"utf-8\\\">\\r\\n <meta http-equiv=\\\"X-UA-Compatible\\\" content=\\\"IE=edge\\\" />\\r\\n <t\"","Identifier":null,"Subproblems":null,"Status":403}
Not getting what i am missing here ?

**Comment by rcladmin** [comment]
The url cannot be found. You can confirm this by pasting the URL in the browser :  http://analytics.clicflyer.com/.well-known/acme-challenge/Amt1jnZaYicwCeARSaRCW5FYfjIdli7MQzltkJCbqPc

You must ensure that the URL can be reached before trying to validate the certificate.

What technology is your site built with : ASP.NET, PHP, Node.js???

**Comment by Ruchi-Bod** [comment]
Hi,
I again tried to create an stand alon certificate & now i can browse the file location at :
 http://analytics.clicflyer.com/.well-known/acme-challenge/ANvvnRpKY63ZCzYFOhRyjAvEqEMSW3k2KadrGOZkxV4
Still i received the following error:
Error:Failed to create certificate with target Stand ALone for host : analytics.clicflyer.com. Could not validate domain for analytics.clicflyer.com with challenge http-01, status reported : Invalid. {"Type":"urn:ietf:params:acme:error:unauthorized","Detail":"The key authorization file from the server did not match this challenge \"ANvvnRpKY63ZCzYFOhRyjAvEqEMSW3k2KadrGOZkxV4.L7EwU-N8pDbEg9-BXShw7PVqk2aaXXT7qa9kPsYo6sw\" != \"ANvvnRpKY63ZCzYFOhRyjAvEqEMSW3k2KadrGOZkxV4.L7EwU-N8pDbEg9-BXShw7PVqk2aaXXT7qa9kPsYo6swss\"","Identifier":null,"Subproblems":null,"Status":403}
Information:Waiting for process to complete ****
My site is developed in MVC .Net & deployed on IIS Server.
Please help.

**Comment by rcladmin** [comment]
You validation token does not match Let's Encrypt validation token

ANvvnRpKY63ZCzYFOhRyjAvEqEMSW3k2KadrGOZkxV4.L7EwU-N8pDbEg9-BXShw7PVqk2aaXXT7qa9kPsYo6swss - Your Token
ANvvnRpKY63ZCzYFOhRyjAvEqEMSW3k2KadrGOZkxV4.L7EwU-N8pDbEg9-BXShw7PVqk2aaXXT7qa9kPsYo6sw - Required Token

You have two additional ss at the end of your token

**Comment by Ruchi-Bod** [comment]
Finally i am able to create an SSL but why this certificate is valid only till 13Nov20

**Comment by rcladmin** [comment]
Let's Encrypt certificate expire in 90 days.
