### ISSUE TITLE
Cannot add a duplicate certificate

### ISSUE THREAD

**Issue by emramirez** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#31]
** What is the error message ?
Cannot add a duplicate certificate

** What is your issue ?
I cannot create the *.sinefi.mx certificate, I have created it 90 days ago, but it disappeared and today I tried to create it again.

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/10326377/90414964-0e5d9c00-e076-11ea-9b15-832929addbd3.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/10326377/90414898-f71eae80-e075-11ea-83e9-377da1d935e8.png">

**Comment by rcladmin** [comment]
You seem to have two RCL Lets Encrypt Account with the same certificate. One account is a personal account that is not supported by the system. You should delete this account.

**Comment by emramirez** [comment]
I can’t access with my personal account (edgar@sinefi.mx), I created a support ticket days ago and the solution was create an AAD/Microsoft account. Can you please delete the certificates associated to edgar@sinefi.mx.

**Comment by rcladmin** [comment]
You will need to delete your SaaS subscription for RCL Lets Encrypy for edgar@sinefi.mx in the Azure portal first.

https://rcl-letsencrypt-auto-ssl.github.io/Lets-Encrypt-Auto/1_subscription.html#unsubscribe

**Comment by emramirez** [comment]
I did it, but it doesn't work. When I deleted my old subscription, I created a new subscription and it was the same than the deleted subscription.

Saludos
Edgar

**Comment by rcladmin** [comment]
You seem to have two active subscriptions, can you verify that one is deleted? Which one was deleted?
