### ISSUE TITLE
Certificate not renew

### ISSUE THREAD

**Issue by carloscds** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#33]
Why certificate not renew?
![image](https://user-images.githubusercontent.com/1697221/91053151-cd770180-e5f8-11ea-9987-3e32c700abe5.png)

**Comment by rcladmin** [comment]
Did you install the auto renew function app?

https://rcl-letsencrypt-auto-ssl.github.io/AutoRenewFunctionDocs/

**Comment by carloscds** [comment]
@rcladmin Yes.

**Comment by rcladmin** [comment]
Take a look at the service principal, set it to 'Account in any organizational directory (Mutli Tenant)

https://rcl-letsencrypt-auto-ssl.github.io/AutoRenewFunctionDocs/installation.html#create-a-service-principal

Test the Certificate List Function or Certificate Function, and let me know what is the output. An error message will be outputted if the function fails

https://rcl-letsencrypt-auto-ssl.github.io/AutoRenewFunctionDocs/installation.html#create-a-service-principal

**Comment by carloscds** [comment]
@rcladmin How can I check that it's everything ok?

**Comment by carloscds** [comment]
@rcladmin One suggestion: Create a "Manual Renew" button

**Comment by rcladmin** [comment]
You can test as follows 

1. Run the Certificate List Function in the Azure Portal 
https://rcl-letsencrypt-auto-ssl.github.io/AutoRenewFunctionDocs/functions.html#certificate-list-function

or 2. Run the Certificate Function in the Azure Portal
https://rcl-letsencrypt-auto-ssl.github.io/AutoRenewFunctionDocs/functions.html#certificate-function

Run the either test and tell me what is the output. Error messages will be posted in the output to help resolve configuration issues.

**Comment by carloscds** [comment]
@rcladmin 
Invalid data caused operation failure. Could not get certificates list. Failure in HTTP Service : Post. Failed response : Unauthorized in HTTP Service : Post.

**Comment by rcladmin** [comment]
Ok, I will try to trouble shoot. I need some information.

1. Did you update your Service Principal to be Multitenant (Access account is any Organizational Directory)
2. Did you set your Service Principal Credentials (client id, tenant id, client secret) in your Function app

**Comment by carloscds** [comment]
@rcladmin Yes, according your tutorial.

**Comment by rcladmin** [comment]
Ok, i am going to trouble shoot the system. This may take some time, I will get back to you as soon as I resolve the problem.

**Comment by rcladmin** [comment]
Can you set the the Service Principal to use 'ID Toekens' instead of 'Access Tokens' and try running the Certificate List function again. ID token are recommended for .NET Core Apps.

**Comment by carloscds** [comment]
@rcladmin Same Error

**Comment by rcladmin** [comment]
Ok, I will continue to test.

**Comment by carloscds** [comment]
@rcladmin Please, consider create a "Manual Update" button on App.

**Comment by rcladmin** [comment]
The setting for the Service Principal is:

1- Single Tenant
2- Implicit flow with ID Token

You can test the Certificate List function now

**Comment by carloscds** [comment]
@rcladmin Now I can list certificate! Thanks! Do you consider create a button to manual renew ?

**Comment by rcladmin** [comment]
You can manually run the Certificate Renew function to renew your certificates

https://rcl-letsencrypt-auto-ssl.github.io/AutoRenewFunctionDocs/functions.html#certificate-renew-automatic-function

You will see the result of the renewal in the Notification page of the app. You can inform me if there are any failures in the certificate renewals.

The 'update' is currently being tested. You can expect to see the 'manual update' button very soon,
