### ISSUE TITLE
Can't login to my subscription - URGENT 

### ISSUE THREAD

**Issue by zukit** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#34]
We have subscribed to your SaaS (goes in Azure by the name CER-Talmudit-Pilot), but I cant login to your Lets Encrypt site. I cant figure out what is the login name. I need to renew my certificates ASAP (expired today).

Please advice,
Roni

**Comment by rcladmin** [comment]
What is the username that you try to login with? Or what is the name (hostname) of the certificate?

**Comment by zukit** [comment]
talmudit.online
meanwhile I deleted the subscription, created a new one and was trying to create a new certificate for talmudit.online but I'm getting the duplicate error. you must delete it ASAP.

**Comment by rcladmin** [comment]
I deleted talmudit.online
