### ISSUE TITLE
Configure your SaaS account on the publisher's website to complete the purchase.

### ISSUE THREAD

**Issue by rparulz** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#35]
** What is the error message ?
[Login screen shows working after putting the username and password but returns back again to login screen]

** What is your issue ?
[Because of the issue unable to configure account and integrate RCL SSL]

**Comment by rcladmin** [comment]
What type of account are you using to sign in ? Is it an Active Directory organization account (Work or School account)?
