### ISSUE TITLE
No responce

### ISSUE THREAD

**Issue by chillyjim** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#5]
I have issued two CSRs and after several hours neither have come back. Thank you.
jholmes@checkpoint.com
jlh@troycivic.org

**Comment by rcladmin** [comment]
What option are you using to create a certificate? Is it Stand Alone Certificate?

**Comment by chillyjim** [comment]
From the homepage, create new ssl/tls certificate->stand alone

I’ve tried not a wild card and server request 

It never gets past “Information:Waiting for process to start ***”

Sent from my iPhone

**Comment by rcladmin** [comment]
Could you tell me the values you entered for:

- Host Name
- Root Domain
- Challenge Type

on the 'Create Stand Alone SSL/TLS Certificate' page

**Comment by chillyjim** [comment]
Please see in-line

[…]

Could you tell me the values you entered for:
·         Host Name *.troycivic.org and gns3.troycivic.org
·         Root Domain troycivic.org
·         Challenge Type DNS

on the 'Create Stand Alone SSL/TLS Certificate' page

**Comment by rcladmin** [comment]
Can you try it again. Ensure you add one host name at a time. We do not support multiple hostnames on a single certificate.

**Comment by chillyjim** [comment]
That was two separate requests. This is the one I just started.

[cid:image001.png@01D5FFBE.93E364C0]

**Comment by rcladmin** [comment]
wait a few minutes for DNS challenge to complete. It sleeps for a few minutes to allow for DNS propogation.

**Comment by chillyjim** [comment]
It worked this time. Thank you.
