### ISSUE TITLE
DNS List Cut Off

### ISSUE THREAD

**Issue by gcliv** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#6]
When attempting to create a certificate for Azure App Service with a DNS challenge, the list of DNS zones in the GUI is cut off after approximately 100 zones.

**Comment by rcladmin** [comment]
You are correct, 100 DNS Zones are returned by default. How may DNS Zones do you require to be returned?

**Comment by gcliv** [comment]
Well I’ve got 136 in that resource group, so I’d say up to 150?

Chris Lincoln
chris@chrislincoln.com

**Comment by rcladmin** [comment]
Ok, I will increase to 150 and get back to you as soon as I am done.

**Comment by rcladmin** [comment]
The returned DNS Zones was increased to 150. You can try it now and tell me if it works.

**Comment by gcliv** [comment]
Looks like it works! Thanks!

Chris Lincoln
chris@chrislincoln.com
