### ISSUE TITLE
Can't delete certificate

### ISSUE THREAD

**Issue by gcliv** [rcl-letsencrypt-auto-ssl/Lets-Encrypt-Auto#8]
** What is the error message ?
Failed to delete certificate for host : <domain>. Value cannot be null. (Parameter 'uriString') 

** What is your issue ?
Trying to delete an existing certificate. I think one of my web devs may have manually removed the certificate. How can I delete it so I can recreate?

**Comment by rcladmin** [comment]
The 'uriString' parameter error was resolved today.
